import { ArrowRight } from "lucide-react";
import Link from "next/link";

import { Button } from "@/components/ui/button";

export function Hero() {
  return (
    <section className="container flex flex-col items-center gap-8 pb-28 pt-20 sm:gap-10">
      
      <h1 className="max-w-4xl text-center font-heading text-4xl font-semibold sm:text-5xl md:text-6xl sm:leading-tight">
        Learn Anything, Instantly
        <br />
      </h1>
      <p className="max-w-lg text-center text-lg text-muted-foreground sm:text-xl">
        Instantly create quizzes, recursively summarize content, chat with content, autogenerated PPTs, and more for all your learning needs.
      </p>
      
        
        <Button size="lg" asChild className="h-12 cursor-pointer text-base sm:h-14 sm:px-10">
          <Link href="/gen/create">Get Started</Link>
        </Button>
      
      <div className="relative w-full max-w-5xl sm:mt-8">
        <div className="rounded-xl border border-border bg-secondary/30 p-8">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="flex flex-col gap-4 p-6 rounded-lg bg-background/80 backdrop-blur-sm border border-border hover:border-primary/50 transition-colors">
              <div className="h-10 w-10 rounded-full bg-primary/10 flex items-center justify-center">
                <svg className="h-5 w-5 text-primary" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
                </svg>
              </div>
              <h3 className="font-semibold text-lg">Interactive Quiz Experience</h3>
              <p className="text-sm text-muted-foreground">Generate and take personalized quizzes instantly. Track your progress and identify areas for improvement with detailed performance analytics.</p>
            </div>

            <div className="flex flex-col gap-4 p-6 rounded-lg bg-background/80 backdrop-blur-sm border border-border hover:border-primary/50 transition-colors">
              <div className="h-10 w-10 rounded-full bg-primary/10 flex items-center justify-center">
                <svg className="h-5 w-5 text-primary" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 10h.01M12 10h.01M16 10h.01M9 16H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-5l-5 5v-5z" />
                </svg>
              </div>
              <h3 className="font-semibold text-lg">AI-Powered Content Chat</h3>
              <p className="text-sm text-muted-foreground">Have interactive conversations with your learning materials. Get instant clarification and deeper insights through natural dialogue.</p>
            </div>

            <div className="flex flex-col gap-4 p-6 rounded-lg bg-background/80 backdrop-blur-sm border border-border hover:border-primary/50 transition-colors">
              <div className="h-10 w-10 rounded-full bg-primary/10 flex items-center justify-center">
                <svg className="h-5 w-5 text-primary" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
                </svg>
              </div>
              <h3 className="font-semibold text-lg">Smart Lesson Generation</h3>
              <p className="text-sm text-muted-foreground">Transform any content into structured learning materials. Get personalized study guides and comprehensive lesson plans.</p>
            </div>

            <div className="flex flex-col gap-4 p-6 rounded-lg bg-background/80 backdrop-blur-sm border border-border hover:border-primary/50 transition-colors">
              <div className="h-10 w-10 rounded-full bg-primary/10 flex items-center justify-center">
                <svg className="h-5 w-5 text-primary" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 12l3-3 3 3 4-4M8 21l4-4 4 4M3 4h18M4 4h16v12a1 1 0 01-1 1H5a1 1 0 01-1-1V4z" />
                </svg>
              </div>
              <h3 className="font-semibold text-lg">Presentation Creator</h3>
              <p className="text-sm text-muted-foreground">Automatically generate professional presentations for teachers and students. Save time with ready-to-use slides that capture key concepts.</p>
            </div>
          </div>
        </div>
        <div className="absolute inset-0 -z-10 bg-primary/20 [filter:blur(180px)]" />
      </div>

      <div className="mt-16 w-full max-w-5xl">
        <div className="rounded-xl border border-border bg-secondary/30 p-8">
          <h2 className="text-center text-2xl font-semibold mb-4">Under Active Development</h2>
          <p className="text-center text-muted-foreground">
            We have many exciting features and refinements planned for the future. We are working hard to bring you new capabilities and improvements that we have planned. 
          </p>
        </div>
      </div>
    </section>
  );
}
